namespace HV3DDUALITY
{
	struct HV3DName {
		String s;
	};

	struct HV3DPath {
		String s;
	};

	struct HV3DFile {
		String s;
	};

	struct HV3DDate {
		String s;
	};

	struct HV3DVersion {
		String s;
	};

	enum HV3DBasicError {
		HV3D_OK			= 0x00000000,
		HV3D_UNKNOWN	= 0x00000001,
		HV3D_OUT_OF_MEM = 0x00000002,
	};

	struct HV3DActivationFactory {
		HV3DName clsid;
		HV3DPath dll;
	};

}

