import "HV3DView.idl";
import "HV3DKeyboardBindings.idl";
import "HV3DMouseBindings.idl";

namespace HV3DDUALITY.HV3DEnvironment {
	struct HV3DEnvironmentCPU {
		HV3DDUALITY.HV3DPath ProjectPath;
		HV3DDUALITY.HV3DPath PluginPath;
	};

	struct HV3DEnvironmentGPU {
		HV3DDUALITY.HV3DView.HV3DRenderingEngine Pipeline;
		HV3DDUALITY.HV3DView.HV3DResolution Resolution;
		HV3DDUALITY.HV3DView.HV3DAA AntiAliassing;
		HV3DDUALITY.HV3DView.HV3DMultiSampling MultiSampling;
		HV3DDUALITY.HV3DView.HV3DSuperSampling SuperSampling;
		HV3DDUALITY.HV3DView.HV3DFilterMode FilterMode;
		HV3DDUALITY.HV3DView.HV3DPixelFilter PixelFilter;
		HV3DDUALITY.HV3DView.HV3DGamma Gamma;
		HV3DDUALITY.HV3DView.HV3DNearPlane NearPlane;
		HV3DDUALITY.HV3DView.HV3DFarPlane FarPlane;
	};

	struct HV3DEnvironmentBindings {
		HV3DDUALITY.HV3DBindings.HV3DKeyboardBindings KeyboardBindings;
		HV3DDUALITY.HV3DBindings.HV3DMouseBindings MouseBindings;
	};

	struct HV3DEnvironmentShell {
		HV3DDUALITY.HV3DName ShellProvider;
		HV3DDUALITY.HV3DDate DateModified;
		HV3DDUALITY.HV3DVersion Version;
		HV3DDUALITY.HV3DActivationClassFactory ClassFactory;
	};

	struct HV3DEnvironmentPlugin {
		HV3DDUALITY.HV3DPath PathJson;
		HV3DDUALITY.HV3DFile FileJson;
		HV3DDUALITY.HV3DDate DateModified;
		HV3DDUALITY.HV3DVersion Version;
	};

	[uuid(C567AE0B-27FD-46EC-B23C-766F91F1DEBA)]
	[version(0x10000001)]
	interface IHV3DHeader : IInspectable
	{
		HRESULT LoadFromFile(HV3DDUALITY.HV3DFile file);

	};

	[uuid(2EB303F0-92A9-4B79-BD23-D2089444A4D4)]
	[version(0x10000001)]
	interface IHV3DCallbackInterface : IInspectable
	{
		void Exit();

	};

	[uuid(23E3D5AD-6C7A-483D-AB2E-166E9CD435BE)]
	[version(0x10000001)]
	interface IHV3DPortalInterface : IInspectable
	{
		void GetCallbackInterface(IHV3DCallbackInterface e);

	};

	[uuid(157F533E-5EFC-48C7-BACA-B506E4857B90)]
	[version(0x10000001)]
	interface IHV3DApplication : IInspectable
	{
		void LoadApplication();

	};

	[uuid(B0344658-8549-4D45-8CBE-96A89144B1AB)]
	[version(0x10000001)]
	interface IHV3DShell : IInspectable
	{
		void NewShell();

	};

	[uuid(EBEF780B-2115-492E-8AC8-47BF7D188ABF)]
	[version(0x10000001)]
	interface IHV3DCluster : IInspectable
	{
		void MountCluster();

	};
	
}