namespace HV3DLoaders
{
    [default_interface]
    runtimeclass HV3DObjLoader
    {
        HV3DObjLoader();

        Windows.Foundation.Collections.IVector<HV3DDUALITY.HV3DTensors.HV3DTriangle> LoadMeshFromFile(String file);

    }

}
