namespace DUALITY
{
    [default_interface]
    runtimeclass HV3DAppFrame : Microsoft.UI.Xaml.Controls.Frame, 
        HV3DDUALITY.HV3DEnvironment.IHV3DCallbackInterface
    {
        HV3DAppFrame();

    }

}
